version: '3'

services:
  gcc:
    image: gcc:4.9
    container_name: exam_gcc
    command: tail -f /dev/null # Avoid container from exiting, usually we run a server so container stays alive
    volumes:
      - /tmp/code:/tmp/code
